version: "3.8"

services:
  app:
    image: alekseysav/ink-master:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql-db:5432/citiesdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgresql-db

  postgresql-db:
    image: postgresql
    environment:
      POSTGRESQL_ROOT_PASSWORD: admin
      POSTGRESQL_DATABASE: citiesdb
    ports:
      - "5432:5432"

  nginx:
    image: public.ecr.aws/nginx/nginx:1.26-alpine-perl
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=postgres
      - NGINX_PORT=8080
    depends_on:
      - postgres
